version: "3.9"
services: 
    db: 
     image: 'mysql8.0'
     ports: 
      - '3305:3305'
     environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user 
      MYSQL_DATABASE: database
      MYSQL_PASSWORD: password
     container_name: docker_sql_db
        
    phpmyadmin: 
     image: phpmyadmin/phpmyadmin
     ports: 
      - '3000:80'
     environment: 
      - PMA_PASSWORD=password
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=user
     links: 
      - db
